In [2]:
import json
import pandas as pd

In [5]:
data = pd.read_csv('Materials\MeteoBlue\dataexport_20210401T195405_hi-res.csv')

C:\Users\Flori\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [16]:
data.head(9)

,location,O.R. Tambo International Airport,Frankfurt am Main,Brussels,Amsterdam,Dubai International Airport,Begumpet Airport,Shanghai Pudong International Airport,Chicago O'Hare International Airport,Comodoro Arturo Merino Benítez International Airport,...,Comodoro Arturo Merino Benítez International Airport.2,O.R. Tambo International Airport.3,Frankfurt am Main.3,Brussels.3,Amsterdam.3,Dubai International Airport.3,Begumpet Airport.3,Shanghai Pudong International Airport.3,Chicago O'Hare International Airport.3,Comodoro Arturo Merino Benítez International Airport.3
0,lat,-26.14984,50.11647,50.86329,52.37008,24.99988,17.49359,31.11631,41.99986,-33.40651,...,-33.40651,-26.14984,50.11647,50.86329,52.37008,24.99988,17.49359,31.11631,41.99986,-33.40651
1,lon,28.27415,8.69360,4.36938,4.91682,55.31250,78.46516,121.72454,-88.12500,-70.78083,...,-70.78083,28.27415,8.69360,4.36938,4.91682,55.31250,78.46516,121.72454,-88.12500,-70.78083
2,asl,1629.447,119.513,48.976,-1.531,82.283,553.200,5.429,226.966,506.974,...,506.974,1629.447,119.513,48.976,-1.531,82.283,553.200,5.429,226.966,506.974
3,variable,Temperature,Temperature,Temperature,Temperature,Temperature,Temperature,Temperature,Temperature,Temperature,...,Wind Speed,Wind Direction,Wind Direction,Wind Direction,Wind Direction,Wind Direction,Wind Direction,Wind Direction,Wind Direction,Wind Direction
4,unit,°C,°C,°C,°C,°C,°C,°C,°C,°C,...,km/h,°,°,°,°,°,°,°,°,°
5,level,2 m elevation corrected,2 m elevation corrected,2 m elevation corrected,2 m elevation corrected,2 m elevation corrected,2 m elevation corrected,2 m elevation corrected,2 m elevation corrected,2 m elevation corrected,...,10 m,10 m,10 m,10 m,10 m,10 m,10 m,10 m,10 m,10 m
6,resolution,hourly,hourly,hourly,hourly,hourly,hourly,hourly,hourly,hourly,...,hourly,hourly,hourly,hourly,hourly,hourly,hourly,hourly,hourly,hourly
7,aggregation,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,timestamp,O.R. Tambo International Airport Temperature [...,Frankfurt am Main Temperature [2 m elevation c...,Brussels Temperature [2 m elevation corrected],Amsterdam Temperature [2 m elevation corrected],Dubai International Airport Temperature [2 m e...,Begumpet Airport Temperature [2 m elevation co...,Shanghai Pudong International Airport Temperat...,Chicago O'Hare International Airport Temperatu...,Comodoro Arturo Merino Benítez International A...,...,Comodoro Arturo Merino Benítez International A...,O.R. Tambo International Airport Wind Directio...,Frankfurt am Main Wind Direction [10 m],Brussels Wind Direction [10 m],Amsterdam Wind Direction [10 m],Dubai International Airport Wind Direction [10 m],Begumpet Airport Wind Direction [10 m],Shanghai Pudong International Airport Wind Dir...,Chicago O'Hare International Airport Wind Dire...,Comodoro Arturo Merino Benítez International A...

In [13]:
tempdata = data[9:]

In [14]:
df["Date"] = pd.to_datetime(df["Date"]).dt.strftime('%Y-%m-%d')

,location,O.R. Tambo International Airport,Frankfurt am Main,Brussels,Amsterdam,Dubai International Airport,Begumpet Airport,Shanghai Pudong International Airport,Chicago O'Hare International Airport,Comodoro Arturo Merino Benítez International Airport,...,Comodoro Arturo Merino Benítez International Airport.2,O.R. Tambo International Airport.3,Frankfurt am Main.3,Brussels.3,Amsterdam.3,Dubai International Airport.3,Begumpet Airport.3,Shanghai Pudong International Airport.3,Chicago O'Hare International Airport.3,Comodoro Arturo Merino Benítez International Airport.3
9,20150101T0000,NaN,2.8123367,2.5663445,1.405546,16.047838,19.430801,0.055787906,-7.5712194,19.050833,...,11.928989,NaN,213.69006,218.85338,220.36453,72.34988,165.96376,320.02908,236.87027,185.19443
10,20150101T0100,NaN,2.7223368,2.2963445,1.285546,15.4778385,19.3208,1.855788,-7.6812196,18.030832,...,11.183201,NaN,225.0,215.94211,218.50066,75.96376,175.23636,323.84183,238.09985,183.69139
11,20150101T0200,NaN,2.7923367,1.5763445,1.0755459,14.9778385,19.7308,3.0257878,-7.7812195,17.350832,...,10.1376915,NaN,258.69006,211.53479,216.67435,78.69006,182.60257,325.6457,240.80252,186.11551
12,20150101T0300,NaN,2.9123366,1.0163444,0.865546,14.457838,20.9108,3.7957878,-7.92122,16.750834,...,8.707238,NaN,290.55603,210.01837,221.28471,83.65981,184.23639,325.9679,243.6579,187.12502
13,20150101T0400,NaN,2.9023366,0.85634446,0.48554596,16.257837,22.7808,4.495788,-8.16122,16.300833,...,8.049845,NaN,261.8699,219.2072,219.80557,85.60129,178.21008,326.30994,246.8014,190.30484